version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
  node: circleci/node@1.1.6

workflows:
  build-test-report:
    jobs:
      - checkout-and-install
      - compile-and-test-contracts:
          requires:
            - checkout-and-install
          # context: BUILD_KEYS
      - lint:
          requires:
            - compile-and-test-contracts
      - contract-size:
          requires:
            - compile-and-test-contracts

jobs:
  checkout-and-install:
    working_directory: ~/squeeth/packages/hardhat
    docker:
      - image: circleci/node:12.22.4
    steps:
      - checkout:
          path: ~/squeeth
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: yarn install
      - save_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - save_cache:
          key: squeeth-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/squeeth

  compile-and-test-contracts:
    working_directory: ~/squeeth/packages/hardhat
    docker:
      - image: circleci/node:12.22.4
    steps:
      - checkout:
          path: ~/squeeth
      - restore_cache:
          key: squeeth-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: Compile Contracts
          command: npx hardhat compile
      - run: 
          name: Unit tests
          command: npx hardhat test --network hardhat
      - save_cache: 
          key: typechain-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - typechain
      - save_cache: 
          key: artifacts-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - artifacts
      # - run:
      #     name: Coverage Report
      #     command: npx hardhat coverage
      # - coveralls/upload:
      #     path_to_lcov: ./coverage/lcov.info
      # - store_artifacts:
      #     path: /coverage
      # - store_artifacts:
      #     path: /coverage.json
  
  lint:
    working_directory: ~/squeeth/packages/hardhat
    docker:
      - image: circleci/node:12.22.4
    steps:
      - checkout:
          path: ~/squeeth
      - restore_cache:
          key: squeeth-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: typechain-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Lint
          command: yarn lint:check
  
  contract-size:
    working_directory: ~/squeeth/packages/hardhat
    docker:
      - image: circleci/node:12.22.4
    steps:
      - checkout:
          path: ~/squeeth
      - restore_cache:
          key: squeeth-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: artifacts-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Check Contracts Size
          command: npx hardhat size-contracts